### ISSUE TITLE
Problem with unit scoped compunit

### ISSUE THREAD

**Issue by finanalyst** [JJ/p6-pod-load#10]
When POD is in a module with a unit scoped compunit, Pod::Load complains about too late to change.

Eg., try following short script assuming it is run in directory of Template::Classic
```
use v6.*;
use Load::Pod;
my $pod = load('lib/Template/Classicpm6';
```

**Comment by JJ** [comment]
Thanks for the report. I vaguely remember this was fixed. Anyway, I'll check it out.

**Comment by finanalyst** [comment]
Fixed. Bump version to force zef to use new version?

**Comment by JJ** [comment]
Let me run more extensive tests to close this...

**Comment by finanalyst** [comment]
Oh. Let me know when you re-publish it.

**Comment by JJ** [comment]
Done and uploaded. Thanks!
