### ISSUE TITLE
Z<> entries are not ignored 

### ISSUE THREAD

**Issue by tbrowder** [JJ/p6-pod-load#14]
Given a chunk of text like this:

    my $s = "Z<this is a comment>";

and executing:

    use Pod::Load;
    my @pod = load $s;

I get an exception

    Undeclared name:
        Z used at line 2

Using latest Raku on Debian Buster.

**Comment by JJ** [comment]
OK, we'll take a look.

**Comment by JJ** [comment]
Working on this. For the time being, I can reproduce it.
