### ISSUE TITLE
Tests fail on Windows

### ISSUE THREAD

**Issue by hankache** [JJ/p6-pod-load#5]
Rakudo 2019.03.1
```
===> Testing: Pod::Load:ver<0.4.0>
# Testing strings
Failed to remove the directory 'C:\Users\naoum\AppData\Local\Temp\B93E2E259914003CBED764A23AD228BC90C786BE': Failed to rmdir: directory not empty
  in sub load at C:\Users\naoum\Desktop\rakudo-star-2019.03\modules\p6-pod-load\lib\Pod\Load.pm6 (Pod::Load) line 81
  in sub load at C:\Users\naoum\Desktop\rakudo-star-2019.03\modules\p6-pod-load\lib\Pod\Load.pm6 (Pod::Load) line 64
  in sub do-the-test at t/01-basic.t line 19
  in block <unit> at t/01-basic.t line 40

===> Testing [FAIL]: Pod::Load:ver<0.4.0>
```

**Comment by JJ** [comment]
Thanks for the report. I'll check it out inmediately. I don't have a
Windows box ready, however. Could you help in case I need some tests?

**Comment by hankache** [comment]
Sure

**Comment by JJ** [comment]
Hum, that line is

    $precomp-store.delete-by-compiler($compiler-id);

That should be a Rakudo bug, I'm afraid... I'll see what happens there...

**Comment by ugexe** [comment]
> @JJ if you're using the method as a generic rm -rf can you instead use https://github.com/labster/p6-file-directory-tree, there is a method called rmtree. Will this fix the issue?

It would have to rely on an implementation detail (that `$compiler-id` represents a folder of the same name).

**Comment by hankache** [comment]
@ugexe what about closing the handle before calling: `$precomp-store.delete-by-compiler($compiler-id);`?

**Comment by JJ** [comment]
I will try to fix this temporarily, but @ugexe is right and it might be better to refactor.

**Comment by JJ** [comment]
OK, I got it tested now in Windows and [reproduce the error](https://ci.appveyor.com/project/JJ/p6-pod-load/builds/23313660/job/jrgococgb1tson6h). @hankache do you think closing the handle will help? @ugexe any suggestion on how to do this?
I've had a look at Perl6::Parser DrForr/perl6-Perl6-Parser#20, but it just passes through Pods (and comments along). I can't use that.
And, at the end of the day, using precomp is (almost) as dangerous as using EVAL (and probably much slower). So I might go back to use that. Any suggestion is welcome.

**Comment by JJ** [comment]
I'm looking at a safer alternative that would include parsing the files
through Perl6::Parser, and then process using EVAL *just* the Perl6::Pod
and Perl6::Comment blocks. That will take some time, through. If it's
urgent, I can just get it to work processing the whole thing through EVAL.

**Comment by hankache** [comment]
@JJ ++
