### ISSUE TITLE
This module fails each time I use it in travis

### ISSUE THREAD

**Issue by antoniogamiz** [JJ/p6-pod-load#7]
This is one of the failing builds: https://travis-ci.org/antoniogamiz/Perl6-Documentable/builds/543102809

**Comment by JJ** [comment]
In which file is it failing? I can't figure it out from the Travis test.

**Comment by JJ** [comment]
I have downloaded it locally and it does not fail with perl6 2019.03.1 Can you please clarify?

**Comment by antoniogamiz** [comment]
It fails with this pod file https://github.com/antoniogamiz/Perl6-Documentable/blob/master/t/pod-test.pod6.
I also have tried locally and it works, that the strange think.

**Comment by JJ** [comment]
Different versions, probably.

I'll add it to the test set and see what happens.

**Comment by antoniogamiz** [comment]
Still failing :/ https://travis-ci.com/antoniogamiz/Perl6-Documentable/builds/115057551?utm_medium=notification&utm_source=email

**Comment by antoniogamiz** [comment]
It's already working so I will close it.
